name: Scheduled Run

on:
  schedule:
    - cron: "0 14 * * *"   # Runs daily at 9 AM Toronto time during EST
  workflow_dispatch:       # Manual run option

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run command
        run: |
          echo "GitHub Action scheduled successfully"
